[dev]
	framework = "#custom"
	targetPort = 8888
	port = 3000
	publish = "dist"
	autoLaunch = false
	command = "npm run dev_frontend --port 8888"
	functions = "./api"

[build]
	publish = "dist"
	command = "npm run generate"
    functions = "./api"

[[redirects]]
	from = "/api/*"
	to = "/.netlify/functions/serverless/:splat"
	status = 200
